import { ReactNode, Suspense } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/app/src/component/layout/Footer'
import BottomNav from '@/app/src/component/layout/BottomNav'
import Toast from '@/app/src/component/common/toast/Toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="kor">
      <body className={inter.className} id="root">
        <div className="flex h-full w-full justify-center">
          <div className="w-[550px] shadow-lg">
            <Suspense>{children}</Suspense>
            <Footer />
            <BottomNav />
          </div>
        </div>
        <Toast />
      </body>
    </html>
  )
}
